## In Langchain, the Agent can access many dataframes at once

### **01: Install all the Required Packages**

In [1]:
!pip install langchain langchain_experimental watermark openai --quiet

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 210.1/210.1 kB 5.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 41.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 63.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 40.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 502.7/502.7 kB 28.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.7/64.7 kB 4.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.0/51.0 kB 3.7 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.32.5 which is incompatible.

### **02: Import All the Required Libraries**

In [2]:
import os
import warnings
warnings.filterwarnings("ignore")

In [4]:
from langchain_experimental.agents.agent_toolkits import create_pandas_dataframe_agent
from langchain.community.llms.OpenAI
import pandas as pd

ModuleNotFoundError: No module named 'langchain.llms'

### **03: Setup the Environment**

In [ ]:
os.environ['OPENAI_API_KEY'] = "Your_Api_Key"

### **04: Data**

In [6]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/refs/heads/master/titanic.csv"
df = pd.read_csv(url)
print(df.shape)
df.head()

(891, 15)

   survived  pclass     sex   age  ...  deck  embark_town  alive  alone
0         0       3    male  22.0  ...   NaN  Southampton     no  False
1         1       1  female  38.0  ...     C    Cherbourg    yes  False
2         1       3  female  26.0  ...   NaN  Southampton    yes   True
3         1       1  female  35.0  ...     C  Southampton    yes  False
4         0       3    male  35.0  ...   NaN  Southampton     no   True

[5 rows x 15 columns]

### **05: Single DataFrame Example**

### **Agents can interact with Single DataFrame**

In [ ]:
llm = OpenAI()

In [ ]:
agent = create_pandas_dataframe_agent(llm, df, verbose = True, allow_dangerous_code = True)

In [ ]:
agent.run("How many rows are there?")

In [ ]:
agent.run("How many people have age more than 23?")

### **06: Multi DataFrame**

### **Agents can also interact with Multiple DataFrames passed in a list**

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    object
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    object
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), float64(2), int64(4), object(7)
memory usage: 92.4+ KB

In [13]:
df['age'].isnull().sum()

np.int64(177)

In [14]:
df1 = df.copy()

In [15]:
df1

     survived  pclass     sex   age  ...  deck  embark_town  alive  alone
0           0       3    male  22.0  ...   NaN  Southampton     no  False
1           1       1  female  38.0  ...     C    Cherbourg    yes  False
2           1       3  female  26.0  ...   NaN  Southampton    yes   True
3           1       1  female  35.0  ...     C  Southampton    yes  False
4           0       3    male  35.0  ...   NaN  Southampton     no   True
..        ...     ...     ...   ...  ...   ...          ...    ...    ...
886         0       2    male  27.0  ...   NaN  Southampton     no   True
887         1       1  female  19.0  ...     B  Southampton    yes   True
888         0       3  female   NaN  ...   NaN  Southampton     no  False
889         1       1    male  26.0  ...     C    Cherbourg    yes   True
890         0       3    male  32.0  ...   NaN   Queenstown     no   True

[891 rows x 15 columns]

In [16]:
df1['age'] = df1['age'].fillna(df1['age'].mean())

In [18]:
df1['age'].isnull().sum()

np.int64(0)

In [ ]:
agent = create_pandas_dataframe_agent(llm, [df, df1], verbose = True, allow_dangerous_code = True)

In [ ]:
agent.run("How many rows in the age column are different?")

In [19]:
df2 = df1.copy()

In [20]:
df2["Age_Multiplicated"] = df1['age'] * 2

In [21]:
df2.head()

   survived  pclass     sex   age  ...  embark_town  alive  alone Age_Multiplicated
0         0       3    male  22.0  ...  Southampton     no  False              44.0
1         1       1  female  38.0  ...    Cherbourg    yes  False              76.0
2         1       3  female  26.0  ...  Southampton    yes   True              52.0
3         1       1  female  35.0  ...  Southampton    yes  False              70.0
4         0       3    male  35.0  ...  Southampton     no   True              70.0

[5 rows x 16 columns]

In [ ]:
agent = create_pandas_dataframe_agent(llm, [df, df1, df2], verbose = True, allow_dangerous_code = True)

In [ ]:
agent.run("Are the number of columns same in all dataframes?")